deploy:
  provider: heroku
  api_key:
    secure: O25dPOlaCe4svdAZlLdArzlc3fzs/EgYC8X9228Ayhb1TeUguo061aTpQaPP0/bzEQnJIruZVOfqSHFTrUtT3ljmDpTXGI8EW9F0TBgKlMeYHq+s+IPFXcZQIot71b0iHFl5c9iQeRoPYpeYeKiz5NN9izFh59LToJTm+IIow6So6VUJ0s6xRYIEUO5ocqTQL2y01GCzJyvqIQWqi6VY8thSZNd3cIFWf8hZOYpBZc0X8pPVwQpKxd0vh6LokxAdVMX7Ra5zADxLM9Eb2dyhj9N/v0ShCmXzW+5P01PJ4xJzNqIa9TKojMTEKZ/RYBH/IU8OId5XUC6WZ66m7y1+rbvprC0ur8XOVJzvF0njyLx+kwAJPvI6UFmKP3JiwfQAh8TNZ25x7cOwddSqh5rD+VsZ2TbTlsaorHiZqF9vPPOYmMmGCkh+w5/pvHyan26/hNQEo0E0mSnUI7IX4HGV2PtejnDZiHA/5f6q0JuHCnp8J8Nd3x/IQwm4epIM+lmu9zr53zB320Pue0c9uuj+UDQXOn7uYNiMh5X7pd59rT6C/r1ZHMFb1fOiCbC0J+k/yiS8Y4t73PWRSQmMKynoNc48muenKHMgI7KOpTKWpC3jaySzmByo287az+ZK5j+o1wLDB9COVuRx5Aj9Djo8kYWy9Ad1sCK31P2V4FyiNPg=
  app: young-peak-27826
  on:
    repo: DavidDoes/mongoose-blog-app
